---
framework: jest
preRun:
     command:
        - npm ci
        - npm run build
        - npm run check-types
        - npm run format:check
        - npm run lint
preMerge:
  pattern:
    - "./test/**/*.spec.ts"
postMerge:
  pattern:
    - "./test/**/*.spec.ts"
configFile: jest.config.js
version: 1.0
